import React, { createContext, useContext, useState, useEffect } from 'react';
import * as SecureStore from 'expo-secure-store';

const translations = {
    en: {
        hello: "Hello",
        farmer: "Farmer Account",
        update_profile: "Update your profile",
        account: "Account",
        my_farms: "My Farms",
        personal_info: "Personal Information",
        preferences: "Preferences",
        settings: "Settings",
        language: "Language",
        support: "Support",
        help_center: "Help Center",
        logout: "Logout",
        deactivate: "Deactivate Account",
        app_language: "App Language",
        scan_plant: "Scan Plant",
        weather_analysis: "Weather Analysis",
        yield_prediction: "Yield Prediction",
        tips_advisory: "Tips & Advisory",
        ai_chat: "AI Chat Assistant",
        scan_history: "Scan History",
        clear_all: "CLEAR",
        filter_scans: "Filter Scans",
        "Healthy Arecanut": "Healthy Arecanut",
        "Fruit Rot (Koleroga / Mahali)": "Fruit Rot (Koleroga / Mahali)",
        "Basal Stem Rot (Anabe Roga)": "Basal Stem Rot (Anabe Roga)",
        "Yellow Leaf Disease (YLD)": "Yellow Leaf Disease (YLD)",
        "Stem Bleeding": "Stem Bleeding",
        "Bud Rot": "Bud Rot",
        "Inflorescence Die Back": "Inflorescence Die Back",
        "Unknown": "Unknown",
        dashboard_title: "Areca Farm Dashboard",
        retry_sync: "Tap to retry",
        force_logout: "Or tap here to Force Logout and refresh token",
        detect_disease: "Detect disease instantly with AI",
        tap_camera: "Tap to open camera",
        farm_health: "Farm Health",
        based_on_scans: "Based on your recent AI scans",
        recent_scans: "Recent Scans",
        view_all: "View All",
        quick_tools: "Quick Tools",
        calc_yield: "Calculate arecanut output per acre",
        seasonal_practices: "Seasonal farming practices",
        weather_insights: "Rainfall and humidity insights",
        ask_agribot: "Ask AgriBot any farming question",
        status_unknown: "Unknown",
        status_optimal: "Optimal (All Clear)",
        status_minor: "Minor Risk Detected",
        status_critical: "Critical Action Needed",
        farming_tips: "Farming Tips",
        privacy_policy: "Privacy Policy",
        "How to Identify Leaf Spot Disease": "How to Identify Leaf Spot Disease",
        "Best Fertilizers for Arecanut": "Best Fertilizers for Arecanut",
        "Irrigation Techniques for Better Yield": "Irrigation Techniques for Better Yield",
        "Seasonal Care for Arecanut Palms": "Seasonal Care for Arecanut Palms",
        "Disease Guide": "Disease Guide",
        "Nutrients": "Nutrients",
        "Water Management": "Water Management",
        "Maintenance": "Maintenance",
        "5 min read": "5 min read",
        "3 min read": "3 min read",
        "4 min read": "4 min read",
        "6 min read": "6 min read"
    },
    kn: {
        hello: "ನಮಸ್ಕಾರ",
        farmer: "ರೈತ ಖಾತೆ",
        update_profile: "ನಿಮ್ಮ ಪ್ರೊಫೈಲ್ ನವೀಕರಿಸಿ",
        account: "ಖಾತೆ",
        my_farms: "ನನ್ನ ತೋಟಗಳು",
        personal_info: "ವೈಯಕ್ತಿಕ ಮಾಹಿತಿ",
        preferences: "ಆದ್ಯತೆಗಳು",
        settings: "ಸೆಟ್ಟಿಂಗ್ಸ್",
        language: "ಭಾಷೆ",
        support: "ಬೆಂಬಲ",
        help_center: "ಸಹಾಯ ಕೇಂದ್ರ",
        logout: "ಲಾಗ್ ಔಟ್",
        deactivate: "ಖಾತೆ ರದ್ದು",
        app_language: "ಅಪ್ಲಿಕೇಶನ್ ಭಾಷೆ",
        scan_plant: "ಸಸ್ಯವನ್ನು ಸ್ಕ್ಯಾನ್ ಮಾಡಿ",
        weather_analysis: "ಹವಾಮಾನ ವಿಶ್ಲೇಷಣೆ",
        yield_prediction: "ಇಳುವರಿ ಭವಿಷ್ಯ",
        tips_advisory: "ಸಲಹೆಗಳು ಮತ್ತು ಮಾರ್ಗದರ್ಶನ",
        ai_chat: "ಮಾಹಿತಿ ಸಹಾಯಕ (AI)",
        scan_history: "ಸ್ಕ್ಯಾನ್ ಇತಿಹಾಸ",
        clear_all: "ಅಳಿಸಿ",
        filter_scans: "ಫಿಲ್ಟರ್",
        "Healthy Arecanut": "ಆರೋಗ್ಯಕರ ಗಿಡ",
        "Fruit Rot (Koleroga / Mahali)": "ಕೊಳೆ ರೋಗ",
        "Basal Stem Rot (Anabe Roga)": "ಅಣಬೆ ರೋಗ",
        "Yellow Leaf Disease (YLD)": "ಹಳದಿ ಎಲೆ ರೋಗ",
        "Stem Bleeding": "ಕಾಂಡ ಸೋರುವಿಕೆ",
        "Bud Rot": "ಸುಳಿ ಕೊಳೆ ರೋಗ",
        "Inflorescence Die Back": "ಸಿಂಗಾರ ಕಮರುವಿಕೆ",
        "Unknown": "ತಿಳಿದಿಲ್ಲ",
        dashboard_title: "ಅಡಿಕೆ ತೋಟದ ಡ್ಯಾಶ್‌ಬೋರ್ಡ್",
        retry_sync: "ಮರುಪ್ರಯತ್ನಿಸಲು ಟ್ಯಾಪ್ ಮಾಡಿ",
        force_logout: "ಲಾಗ್ ಔಟ್ ಮಾಡಲು ಇಲ್ಲಿ ಟ್ಯಾಪ್ ಮಾಡಿ",
        detect_disease: "AI ಸಹಾಯದಿಂದ ರೋಗಗಳನ್ನು ತಕ್ಷಣ ಪತ್ತೆಹಚ್ಚಿ",
        tap_camera: "ಕ್ಯಾಮೆರಾ ತೆರೆಯಲು ಟ್ಯಾಪ್ ಮಾಡಿ",
        farm_health: "ತೋಟದ ಆರೋಗ್ಯ",
        based_on_scans: "ನಿಮ್ಮ ಇತ್ತೀಚಿನ AI ಸ್ಕ್ಯಾನ್‌ಗಳ ಆಧಾರದ ಮೇಲೆ",
        recent_scans: "ಇತ್ತೀಚಿನ ಸ್ಕ್ಯಾನ್‌ಗಳು",
        view_all: "ಎಲ್ಲವನ್ನೂ ವೀಕ್ಷಿಸಿ",
        quick_tools: "ತ್ವರಿತ ಸಾಧನಗಳು",
        calc_yield: "ಪ್ರತಿ ಎಕರೆಗೆ ಅಡಿಕೆ ಇಳುವರಿಯನ್ನು ಲೆಕ್ಕಹಾಕಿ",
        seasonal_practices: "ಕಾಲೋಚಿತ ಕೃಷಿ ಪದ್ಧತಿಗಳು",
        weather_insights: "ಮಳೆ ಮತ್ತು ಆರ್ದ್ರತೆಯ ಮಾಹಿತಿ",
        ask_agribot: "ಆಗ್ರಿಬಾಟ್‌ಗೆ ಕೃಷಿ ಪ್ರಶ್ನೆಗಳನ್ನು ಕೇಳಿ",
        status_unknown: "ತಿಳಿದಿಲ್ಲ",
        status_optimal: "ಉತ್ತಮ (ಎಲ್ಲವೂ ಸರಿ)",
        status_minor: "ಸಣ್ಣ ಅಪಾಯ ಪತ್ತೆಯಾಗಿದೆ",
        status_critical: "ತಕ್ಷಣದ ಕ್ರಮದ ಅಗತ್ಯವಿದೆ",
        farming_tips: "ಕೃಷಿ ಸಲಹೆಗಳು",
        privacy_policy: "ಗೌಪ್ಯತೆ ನೀತಿ",
        "How to Identify Leaf Spot Disease": "ಎಲೆ ಚುಕ್ಕೆ ರೋಗವನ್ನು ಪತ್ತೆಹಚ್ಚುವುದು ಹೇಗೆ",
        "Disease Guide": "ರೋಗ ಮಾರ್ಗದರ್ಶಿ",
        "5 min read": "5 ನಿಮಿಷದ ಓದು",
        "Best Fertilizers for Arecanut": "ಅಡಿಕೆಗೆ ಅತ್ಯುತ್ತಮ ರಸಗೊಬ್ಬರಗಳು",
        "Nutrients": "ಪೋಷಕಾಂಶಗಳು",
        "3 min read": "3 ನಿಮಿಷದ ಓದು",
        "Irrigation Techniques for Better Yield": "ಉತ್ತಮ ಇಳುವರಿಗಾಗಿ ನೀರಾವರಿ ತಂತ್ರಗಳು",
        "Water Management": "ನೀರಿನ ನಿರ್ವಹಣೆ",
        "4 min read": "4 ನಿಮಿಷದ ಓದು",
        "Seasonal Care for Arecanut Palms": "ಅಡಿಕೆ ಮರಗಳಿಗೆ ಕಾಲೋಚಿತ ಆರೈಕೆ",
        "Maintenance": "ನಿರ್ವಹಣೆ",
        "6 min read": "6 ನಿಮಿಷದ ಓದು"
    },
    ml: {
        hello: "നമസ്കാരം",
        farmer: "കർഷക അക്കൗണ്ട്",
        update_profile: "പ്രൊഫൈൽ അപ്ഡേറ്റ് ചെയ്യുക",
        account: "അക്കൗണ്ട്",
        my_farms: "എന്റെ കൃഷിയിടങ്ങൾ",
        personal_info: "വ്യക്തിഗത വിവരങ്ങൾ",
        preferences: "മുൻഗണനകൾ",
        settings: "സജ്ജീകരണങ്ങൾ",
        language: "ഭാഷ",
        support: "പിന്തുണ",
        help_center: "സഹായ കേന്ദ്രം",
        logout: "ലോഗ് ഔട്ട്",
        deactivate: "അക്കൗണ്ട് നിർജ്ജീവമാക്കുക",
        app_language: "ആപ്പ് ഭാഷ",
        scan_plant: "സസ്യം സ്കാൻ ചെയ്യുക",
        weather_analysis: "കാലാവസ്ഥാ വിശകലനം",
        yield_prediction: "വിളവ് പ്രവചനം",
        tips_advisory: "നുറുങ്ങുകളും ഉപദേശങ്ങളും",
        ai_chat: "AI ചാറ്റ് സഹായി",
        scan_history: "സ്കാൻ ചരിത്രം",
        clear_all: "എല്ലാം മായ്ക്കുക",
        filter_scans: "ഫിൽറ്റർ",
        "Healthy Arecanut": "ആരോഗ്യമുള്ള കമുക്",
        "Fruit Rot (Koleroga / Mahali)": "മഹാളി രോഗം (അഴുകൽ)",
        "Basal Stem Rot (Anabe Roga)": "അടിനമ്പ് അഴുകൽ",
        "Yellow Leaf Disease (YLD)": "മഞ്ഞളിപ്പ് രോഗം",
        "Stem Bleeding": "തണ്ട് ചോരുന്ന രോഗം",
        "Bud Rot": "കൂമ്പ് ചീയൽ",
        "Inflorescence Die Back": "പൂങ്കുല കരിയൽ",
        "Unknown": "അജ്ഞാതം",
        dashboard_title: "അടയ്ക്ക ഫാം ഡാഷ്‌ബോർഡ്",
        retry_sync: "വീണ്ടും ശ്രമിക്കാൻ ടാപ്പ് ചെയ്യുക",
        force_logout: "ലॉग ഔട്ട് ചെയ്യാൻ ഇവിടെ ടാപ്പ് ചെയ്യുക",
        detect_disease: "AI ഉപയോഗിച്ച് രോഗം വേഗത്തിൽ കണ്ടെത്തുക",
        tap_camera: "ക്യാമറ തുറക്കാൻ ടാപ്പ് ചെയ്യുക",
        farm_health: "തോട്ടത്തിന്റെ ആരോഗ്യം",
        based_on_scans: "നിങ്ങളുടെ സമീപകാല AI സ്കാനുകളുടെ അടിസ്ഥാനത്തിൽ",
        recent_scans: "സമീപകാല സ്കാനുകൾ",
        view_all: "എല്ലാം കാണുക",
        quick_tools: "ദ്രുത ഉപകരണങ്ങൾ",
        calc_yield: "ഒരു ഏക്കറിലെ അടയ്ക്ക വിളവ് കണക്കാക്കുക",
        seasonal_practices: "കാലാവസ്ഥയ്ക്കനുസരിച്ചുള്ള കാർഷിക രീതികൾ",
        weather_insights: "മഴയുടെയും ആർദ്രതയുടെയും വിവരങ്ങൾ",
        ask_agribot: "AgriBot-നോട് കാര്‍ഷിക സംശയങ്ങള്‍ ചോദിക്കുക",
        status_unknown: "അജ്ഞാതം",
        status_optimal: "മികച്ചത് (കുഴപ്പമില്ല)",
        status_minor: "ചെറിയ അപകടസാധ്യത",
        status_critical: "ഉടൻ ശ്രദ്ധിക്കേണ്ടതുണ്ട്",
        farming_tips: "കാർഷിക നുറുങ്ങുകൾ",
        privacy_policy: "സ്വകാര്യതാ നയം",
        "How to Identify Leaf Spot Disease": "ഇലപ്പുള്ളി രോഗം എങ്ങനെ തിരിച്ചറിയാം",
        "Disease Guide": "രോഗ മാർഗ്ഗരേഖ",
        "5 min read": "5 മിനിറ്റ് വായന",
        "Best Fertilizers for Arecanut": "കമുകിനുള്ള മികച്ച വളങ്ങൾ",
        "Nutrients": "പോഷകങ്ങൾ",
        "3 min read": "3 മിനിറ്റ് വായന",
        "Irrigation Techniques for Better Yield": "മികച്ച വിളവിനുള്ള ജലസേചന രീതികൾ",
        "Water Management": "ജല പരിപാലനം",
        "4 min read": "4 മിനിറ്റ് വായന",
        "Seasonal Care for Arecanut Palms": "കമുകിന്റെ കാലാനുസൃത പരിചരണം",
        "Maintenance": "പരിപാലനം",
        "6 min read": "6 മിനിറ്റ് വായന"
    },
    hi: {
        hello: "नमस्ते",
        farmer: "किसान खाता",
        update_profile: "प्रोफ़ाइल अपडेट करें",
        account: "खाता",
        my_farms: "मेरे खेत",
        personal_info: "व्यक्तिगत जानकारी",
        preferences: "प्राथमिकताएं",
        settings: "सेटिंग्स",
        language: "भाषा",
        support: "सहायता",
        help_center: "सहायता केंद्र",
        logout: "लॉग आउट",
        deactivate: "खाता निष्क्रिय करें",
        app_language: "ऐप की भाषा",
        scan_plant: "पौधे को स्कैन करें",
        weather_analysis: "मौसम विश्लेषण",
        yield_prediction: "उपज की भविष्यवाणी",
        tips_advisory: "सुझाव और सलाह",
        ai_chat: "एआई चैट सहायक",
        scan_history: "स्कैन इतिहास",
        clear_all: "सब मिटाएं",
        filter_scans: "फ़िल्टर",
        "Healthy Arecanut": "स्वस्थ सुपारी",
        "Fruit Rot (Koleroga / Mahali)": "फल सड़न (कोलेरोगा / महाली)",
        "Basal Stem Rot (Anabe Roga)": "जड़ सड़न (अनाबे रोग)",
        "Yellow Leaf Disease (YLD)": "पीली पत्ती रोग (YLD)",
        "Stem Bleeding": "तना रिसाव",
        "Bud Rot": "कली सड़न",
        "Inflorescence Die Back": "पुष्पगुच्छ का सूखना",
        "Unknown": "अज्ञात",
        dashboard_title: "सुपारी फार्म डैशबोर्ड",
        retry_sync: "पुनः प्रयास करें",
        force_logout: "लॉग आउट करने के लिए यहां टैप करें",
        detect_disease: "AI द्वारा बीमारी का तुरंत पता लगाएं",
        tap_camera: "कैमरा खोलने के लिए टैप करें",
        farm_health: "खेत की स्थिति",
        based_on_scans: "आपके हालिया AI स्कैन के आधार पर",
        recent_scans: "हाल के स्कैन",
        view_all: "सभी देखें",
        quick_tools: "त्वरित उपकरण",
        calc_yield: "प्रति एकड़ सुपारी उपज की गणना करें",
        seasonal_practices: "मौसमी कृषि पद्धतियां",
        weather_insights: "बारिश और नमी की जानकारी",
        ask_agribot: "AgriBot से कृषि संबंधी सवाल पूछें",
        status_unknown: "अज्ञात",
        status_optimal: "उत्तम (सब ठीक है)",
        status_minor: "मामूली जोखिम",
        status_critical: "तत्काल कार्रवाई आवश्यक",
        farming_tips: "कृषि युक्तियाँ",
        privacy_policy: "गोपनीयता नीति",
        "How to Identify Leaf Spot Disease": "लीफ स्पॉट रोग की पहचान कैसे करें",
        "Disease Guide": "रोग मार्गदर्शिका",
        "5 min read": "5 मिनट पढ़ें",
        "Best Fertilizers for Arecanut": "सुपारी के लिए सर्वोत्तम उर्वरक",
        "Nutrients": "पोषक तत्व",
        "3 min read": "3 मिनट पढ़ें",
        "Irrigation Techniques for Better Yield": "बेहतर उपज के लिए सिंचाई तकनीक",
        "Water Management": "जल प्रबंधन",
        "4 min read": "4 मिनट पढ़ें",
        "Seasonal Care for Arecanut Palms": "सुपारी के पेड़ों की मौसमी देखभाल",
        "Maintenance": "रखरखाव",
        "6 min read": "6 मिनट पढ़ें"
    },
    ta: {
        hello: "வணக்கம்",
        farmer: "விவசாயி கணக்கு",
        update_profile: "சுயவிவரத்தைப் புதுப்பிக்கவும்",
        account: "கணக்கு",
        my_farms: "என் பண்ணைகள்",
        personal_info: "தனிப்பட்ட தகவல்",
        preferences: "விருப்பங்கள்",
        settings: "அமைப்புகள்",
        language: "மொழி",
        support: "ஆதரவு",
        help_center: "உதவி மையம்",
        logout: "வெளியேறு",
        deactivate: "கணக்கை முடக்கு",
        app_language: "பயன்பாட்டு மொழி",
        scan_plant: "தாவரத்தை ஸ்கேன் செய்",
        weather_analysis: "வானிலை பகுப்பாய்வு",
        yield_prediction: "மகசூல் கணிப்பு",
        tips_advisory: "குறிப்புகள் மற்றும் ஆலோசனை",
        ai_chat: "எஐ அரட்டை உதவியாளர்",
        scan_history: "ஸ்கேன் வரலாறு",
        clear_all: "அனைத்தையும் அழி",
        filter_scans: "வடிகட்டு",
        "Healthy Arecanut": "ஆரோக்கியமான பாக்கு",
        "Fruit Rot (Koleroga / Mahali)": "பழ அழுகல் (கொலேரோகா / மகாளி)",
        "Basal Stem Rot (Anabe Roga)": "அடிப்பகுதி அழுகல்",
        "Yellow Leaf Disease (YLD)": "மஞ்சள் இலை நோய்",
        "Stem Bleeding": "தண்டு இரத்தப்போக்கு",
        "Bud Rot": "மொட்டு அழுகல்",
        "Inflorescence Die Back": "பாளை கருகல்",
        "Unknown": "தெரியவில்லை",
        dashboard_title: "பாக்கு பண்ணை டாஷ்போர்டு",
        retry_sync: "மீண்டும் முயற்சிக்க தட்டவும்",
        force_logout: "வெளியேற இங்கே தட்டவும்",
        detect_disease: "AI மூலம் நோயை விரைவாக கண்டறியுங்கள்",
        tap_camera: "கேமராவைத் திறக்க தட்டவும்",
        farm_health: "பண்ணையின் ஆரோக்கியம்",
        based_on_scans: "உங்கள் சமீபத்திய AI ஸ்கேன்களின் அடிப்படையில்",
        recent_scans: "சமீபத்திய ஸ்கேன்கள்",
        view_all: "அனைத்தையும் காண்க",
        quick_tools: "விரைவு கருவிகள்",
        calc_yield: "ஒரு ஏக்கருக்கான மகசூலை கணக்கிடவும்",
        seasonal_practices: "பருவகால விவசாய நடைமுறைகள்",
        weather_insights: "மழை மற்றும் ஈரப்பதம் தகவல்கள்",
        ask_agribot: "AgriBot-டம் ஏதேனும் விவசாய கேள்விகளை கேளுங்கள்",
        status_unknown: "தெரியவில்லை",
        status_optimal: "மிகவும் நன்று (எல்லாம் சரி)",
        status_minor: "சிறிய ஆபத்து உள்ளது",
        status_critical: "உடனடி நடவடிக்கை தேவை",
        farming_tips: "விவசாய குறிப்புகள்",
        privacy_policy: "தனியுரிமை கொள்கை",
        "How to Identify Leaf Spot Disease": "இலைப் புள்ளி நோயை எப்படிக் கண்டறிவது",
        "Disease Guide": "நோய் வழிகாட்டி",
        "5 min read": "5 நிமிட வாசிப்பு",
        "Best Fertilizers for Arecanut": "பாக்குக்கான சிறந்த உரங்கள்",
        "Nutrients": "ஊட்டச்சத்துக்கள்",
        "3 min read": "3 நிமிட வாசிப்பு",
        "Irrigation Techniques for Better Yield": "சிறந்த மகசூலுக்கான நீர்ப்பாசன நுட்பங்கள்",
        "Water Management": "நீர் மேலாண்மை",
        "4 min read": "4 நிமிட வாசிப்பு",
        "Seasonal Care for Arecanut Palms": "பாக்கு மரங்களுக்கான பருவகால பராமரிப்பு",
        "Maintenance": "பராமரிப்பு",
        "6 min read": "6 நிமிட வாசிப்பு"
    },
    te: {
        hello: "నమస్కారం",
        farmer: "రైతు ఖాతా",
        update_profile: "ప్రొఫైల్‌ను నవీకరించండి",
        account: "ఖాతా",
        my_farms: "నా పొలాలు",
        personal_info: "వ్యక్తిగత సమాచారం",
        preferences: "ప్రాధాన్యతలు",
        settings: "సెట్టింగులు",
        language: "భాష",
        support: "మద్దతు",
        help_center: "సహాయ కేంద్రం",
        logout: "లాగ్ అవుట్",
        deactivate: "ఖాతాను నిష్క్రియం చేయండి",
        app_language: "యాప్ భాష",
        scan_plant: "మొక్కను స్కాన్ చేయండి",
        weather_analysis: "వాతావరణ విశ్లేషణ",
        yield_prediction: "దిగుబడి అంచనా",
        tips_advisory: "చిట్కాలు మరియు సలహా",
        ai_chat: "AI చాట్ అసిస్టెంట్",
        scan_history: "స్కాన్ చరిత్ర",
        clear_all: "అన్నీ క్లియర్ చేయండి",
        filter_scans: "ఫిల్టర్",
        "Healthy Arecanut": "ఆరోగ్యకరమైన పోక",
        "Fruit Rot (Koleroga / Mahali)": "పండు కుళ్లు (కొలెరోగా / మహాలి)",
        "Basal Stem Rot (Anabe Roga)": "కింది కాండం కుళ్లు",
        "Yellow Leaf Disease (YLD)": "పసుపు ఆకు తెగులు",
        "Stem Bleeding": "కాండం రక్తస్రావం",
        "Bud Rot": "మొగ్గ కుళ్లు",
        "Inflorescence Die Back": "పూలగుత్తి ఎండు తెగులు",
        "Unknown": "తెలియదు",
        dashboard_title: "పోక తోట డాష్‌బోర్డు",
        retry_sync: "మళ్లీ ప్రయత్నించడానికి నొక్కండి",
        force_logout: "లాగ్ అవుట్ చేయడానికి ఇక్కడ నొక్కండి",
        detect_disease: "AI ద్వారా వ్యాధిని వెంటనే గుర్తించండి",
        tap_camera: "కెమెరాను తెరవడానికి నొక్కండి",
        farm_health: "తోట ఆరోగ్యం",
        based_on_scans: "మీ ఇటీవలి AI స్కాన్‌ల ఆధారంగా",
        recent_scans: "ఇటీవలి స్కాన్‌లు",
        view_all: "అన్నీ చూడండి",
        quick_tools: "త్వరిత సాధనాలు",
        calc_yield: "ఎకరాకు పోక దిగుబడిని లెక్కించండి",
        seasonal_practices: "కాలానుగుణ వ్యవసాయ పద్ధతులు",
        weather_insights: "వర్షం మరియు తేమ అంతర్దృష్టులు",
        ask_agribot: "అగ్రిబాట్‌ని ఏదైనా వ్యవసాయ ప్రశ్న అడగండి",
        status_unknown: "తెలియదు",
        status_optimal: "అద్భుతం (అంతా బాగుంది)",
        status_minor: "చిన్న ప్రమాదం కనుగొనబడింది",
        status_critical: "తక్షణ చర్య అవసరం",
        farming_tips: "వ్యవసాయ చిట్కాలు",
        privacy_policy: "గోప్యతా విధానం",
        "How to Identify Leaf Spot Disease": "ఆకు మచ్చ తెగులును గుర్తించడం ఎలా",
        "Disease Guide": "వ్యాధి మార్గదర్శి",
        "5 min read": "5 నిమిషాల పఠనం",
        "Best Fertilizers for Arecanut": "పోక చెట్లకు ఉత్తమ ఎరువులు",
        "Nutrients": "పోషకాలు",
        "3 min read": "3 నిమిషాల పఠనం",
        "Irrigation Techniques for Better Yield": "మెరుగైన దిగుబడి కోసం నీటి పారుదల పద్ధతులు",
        "Water Management": "నీటి నిర్వహణ",
        "4 min read": "4 నిమిషాల పఠనం",
        "Seasonal Care for Arecanut Palms": "పోక చెట్లకు కాలానుగుణ సంరక్షణ",
        "Maintenance": "నిర్వహణ",
        "6 min read": "6 నిమిషాల పఠనం"
    },
    tu: {
        hello: "ಸೊಲ್ಮೆಲು",
        farmer: "ಕೃಷಿಕೆರೆ ಅಕೌಂಟ್",
        update_profile: "ಪ್ರೊಫೈಲ್ ಅಪ್ಡೇಟ್ ಮಲ್ಪುಲೆ",
        account: "ಅಕೌಂಟ್",
        my_farms: "ಎನ್ನ ತೋಟೊಲು",
        personal_info: "ಎನ್ನ ಮಾಹಿತಿ",
        preferences: "ಆದ್ಯತೆಲು",
        settings: "ಸೆಟ್ಟಿಂಗ್ಸ್",
        language: "ಬಾಸೆ",
        support: "ಬೆಂಬಲ",
        help_center: "ಸಹಾಯ ಕೇಂದ್ರ",
        logout: "ಲಾಗ್ ಔಟ್",
        deactivate: "ಅಕೌಂಟ್ ರದ್ದು ಮಲ್ಪುಲೆ",
        app_language: "ಆಪ್ ಬಾಸೆ",
        scan_plant: "ದೈ ಸ್ಕ್ಯಾನ್ ಮಲ್ಪುಲೆ",
        weather_analysis: "ಹವಾಮಾನ ವಿಶ್ಲೇಷಣೆ",
        yield_prediction: "ಇಳುವರಿ ಲೆಕ್ಕ ಮಲ್ಪುಲೆ",
        tips_advisory: "ಸಲಹೆಲು",
        ai_chat: "AI ಚಾಟ್ ಸಹಾಯಕ",
        scan_history: "ಸ್ಕ್ಯಾನ್ ಇತಿಹಾಸ",
        clear_all: "ಮಾಜಾಲೆ",
        filter_scans: "ಫಿಲ್ಟರ್ ಮಲ್ಪುಲೆ",
        "Healthy Arecanut": "ಆರೋಗ್ಯಕರ ದೈ",
        "Fruit Rot (Koleroga / Mahali)": "ಕೊಳೆ ರೋಗ (ಮಹಾಲಿ)",
        "Basal Stem Rot (Anabe Roga)": "ಅಣಬೆ ರೋಗ",
        "Yellow Leaf Disease (YLD)": "ಮಂಜಲ್ ಇರೆತ ರೋಗ (YLD)",
        "Stem Bleeding": "ಕಾಂಡ ಸೋರುನ ರೋಗ",
        "Bud Rot": "ಸುಳಿ ಕೊಳೆ ರೋಗ",
        "Inflorescence Die Back": "ಸಿಂಗಾರ ಕೊಳೆ",
        "Unknown": "ಗೊತ್ತಿಜ್ಜಿ",
        dashboard_title: "ಅಡಿಕೆ ತೋಟದ ಡ್ಯಾಶ್‌ಬೋರ್ಡ್",
        retry_sync: "ಪಿರ ಪ್ರಯತ್ನ ಮಲ್ಪುಲೆ",
        force_logout: "ಲಾಗ್ ಔಟ್ ಮಲ್ಪೆರೆ ಮುಲ್ಪ ಒತ್ತುಲೆ",
        detect_disease: "AI ಮುಖಾಂತರ ರೋಗೊನು ನಾಡ್'ಲೆ",
        tap_camera: "ಕ್ಯಾಮೆರಾ ದೆಪ್ಪೆರೆ ಒತ್ತುಲೆ",
        farm_health: "ತೋಟದ ಪರಿಸ್ಥಿತಿ",
        based_on_scans: "ಇರೆನ ಇತ್ತೀಚೆಗದ AI ಸ್ಕ್ಯಾನ್‌ದ ಆಧಾರದ ಮಿತ್ತ್",
        recent_scans: "ಇತ್ತೀಚೆಗದ ಸ್ಕ್ಯಾನ್‌ಲು",
        view_all: "ಮಾತಲ ತೂಲೆ",
        quick_tools: "ತ್ವರಿತ ಸಾಧನೊಲು",
        calc_yield: "ಪ್ರತಿ ಎಕರೆಗ್ ಇಳುವರಿ ಲೆಕ್ಕ ಮಲ್ಪುಲೆ",
        seasonal_practices: "ಕಾಲೋಚಿತ ಕೃಷಿ ಪದ್ಧತಿಲು",
        weather_insights: "ಬರ್ಸ ಬೊಕ್ಕ ಆರ್ದ್ರತೆದ ಮಾಹಿತಿ",
        ask_agribot: "ಕೃಷಿಬಾಟ್'ಡ ಕೃಷಿ ಪ್ರಶ್ನೆ ಕೇನ್ಲೆ",
        status_unknown: "ಗೊತ್ತಿಜ್ಜಿ",
        status_optimal: "ಉತ್ತಮ (ಮಾತ ಸರಿ ಉಂಡು)",
        status_minor: "ಎಲ್ಯ ಅಪಾಯ ಉಂಡು",
        status_critical: "ತಕ್ಷಣದ ಕ್ರಮ ಬೋಡು",
        farming_tips: "ಕೃಷಿ ಸಲಹೆಲು",
        privacy_policy: "ಗೌಪ್ಯತೆ ನೀತಿ",
        "How to Identify Leaf Spot Disease": "ಎಲೆ ಚುಕ್ಕೆ ರೋಗೊನು ನಾಡ್ಯರೆ ಎಂಚ",
        "Disease Guide": "ರೋಗ ಮಾರ್ಗದರ್ಶಿ",
        "5 min read": "5 ನಿಮಿಷ ಓದು",
        "Best Fertilizers for Arecanut": "ಅಡಿಕೆಗ್ ಎಡ್ಡೆ ರಸಗೊಬ್ಬರ",
        "Nutrients": "ಪೋಷಕಾಂಶೊಲು",
        "3 min read": "3 ನಿಮಿಷ ಓದು",
        "Irrigation Techniques for Better Yield": "ಎಡ್ಡೆ ಇಳುವರಿಗ್ ನೀರಾವರಿ ತಂತ್ರ",
        "Water Management": "ನೀರ್ ನಿರ್ವಹಣೆ",
        "4 min read": "4 ನಿಮಿಷ ಓದು",
        "Seasonal Care for Arecanut Palms": "ಅಡಿಕೆ ಮರಕ್ ಕಾಲೋಚಿತ ಆರೈಕೆ",
        "Maintenance": "ನಿರ್ವಹಣೆ",
        "6 min read": "6 ನಿಮಿಷ ಓದು"
    },
    ar: {
        hello: "ನಮಸ್ಕಾರ",
        farmer: "ಕೃಷಿಕರ ಖಾತೆ",
        update_profile: "ಪ್ರೊಫೈಲ್ ಅಪ್ಡೇಟ್ ಮಾಡಿ",
        account: "ಖಾತೆ",
        my_farms: "ನನ್ನ ತೋಟಗಳು",
        personal_info: "ವೈಯಕ್ತಿಕ ಮಾಹಿತಿ",
        preferences: "ಆದ್ಯತೆಗಳು",
        settings: "ಸೆಟ್ಟಿಂಗ್ಸ್",
        language: "ಭಾಷೆ",
        support: "ಬೆಂಬಲ",
        help_center: "ಸಹಾಯ ಕೇಂದ್ರ",
        logout: "ಲಾಗ್ ಔಟ್",
        deactivate: "ಖಾತೆ ರದ್ದು",
        app_language: "ಆಪ್ ಭಾಷೆ",
        scan_plant: "ಗಿಡ ಸ್ಕ್ಯಾನ್ ಮಾಡಿ",
        weather_analysis: "ಹವಾಮಾನ ವಿಶ್ಲೇಷಣೆ",
        yield_prediction: "ಇಳುವರಿ ಲೆಕ್ಕಾಚಾರ",
        tips_advisory: "ಸಲಹೆಗಳು",
        ai_chat: "AI ಸಹಾಯಕ",
        scan_history: "ಸ್ಕ್ಯಾನ್ ಇತಿಹಾಸ",
        clear_all: "ಅಳಿಸಿ",
        filter_scans: "ಫಿಲ್ಟರ್",
        "Healthy Arecanut": "ಆರೋಗ್ಯಕರ ಗಿಡ",
        "Fruit Rot (Koleroga / Mahali)": "ಕೊಳೆ ರೋಗ",
        "Basal Stem Rot (Anabe Roga)": "ಅಣಬೆ ರೋಗ",
        "Yellow Leaf Disease (YLD)": "ಹಳದಿ ಎಲೆ ರೋಗ",
        "Stem Bleeding": "ಕಾಂಡ ಸೋರುವ ರೋಗ",
        "Bud Rot": "ಸುಳಿ ಕೊಳೆ",
        "Inflorescence Die Back": "ಸಿಂಗಾರ ಕಮರುವಿಕೆ",
        "Unknown": "ತಿಳಿದಿಲ್ಲ",
        dashboard_title: "ಅಡಿಕೆ ತೋಟದ ಡೆಸ್ಕ್",
        retry_sync: "ಮರುಪ್ರಯತ್ನಿಸಲು ಒತ್ತಿರಿ",
        force_logout: "ಲಾಗ್ ಔಟ್ ಮಾಡಲು ಇಲ್ಲಿ ಒತ್ತಿರಿ",
        detect_disease: "AI ನಿಂದ ರೋಗವನ್ನು ತಕ್ಷಣ ಪತ್ತೆಹಚ್ಚಿ",
        tap_camera: "ಕ್ಯಾಮೆರಾ ತೆರೆಯಲು ಒತ್ತಿರಿ",
        farm_health: "ತೋಟದ ಆರೋಗ್ಯ",
        based_on_scans: "ನಿಮ್ಮ ಇತ್ತೀಚಿನ AI ಸ್ಕ್ಯಾನ್‌ಗಳ ಆಧಾರದ ಮೇಲೆ",
        recent_scans: "ಇತ್ತೀಚಿನ ಸ್ಕ್ಯಾನ್‌ಗಳು",
        view_all: "ಎಲ್ಲವನ್ನೂ ವೀಕ್ಷಿಸಿ",
        quick_tools: "ತ್ವರಿತ ಪರಿಕರಗಳು",
        calc_yield: "ಪ್ರತಿ ಎಕರೆಗೆ ಅಡಿಕೆ ಇಳುವರಿಯನ್ನು ಲೆಕ್ಕಹಾಕಿ",
        seasonal_practices: "ಕಾಲೋಚಿತ ಕೃಷಿ ಪದ್ಧತಿಗಳು",
        weather_insights: "ಮಳೆ ಮತ್ತು ಆರ್ದ್ರತೆಯ ಒಳನೋಟಗಳು",
        ask_agribot: "ಕೃಷಿಬಾಟ್ ಅನ್ನು ಕೃಷಿ ಪ್ರಶ್ನೆ ಕೇಳಿ",
        status_unknown: "ತಿಳಿದಿಲ್ಲ",
        status_optimal: "ಉತ್ತಮ (ಎಲ್ಲವೂ ಸರಿ)",
        status_minor: "ಸಣ್ಣ ಅಪಾಯ ಪತ್ತೆಯಾಗಿದೆ",
        status_critical: "ತಕ್ಷಣದ ಕ್ರಮದ ಅಗತ್ಯವಿದೆ",
        farming_tips: "ಕೃಷಿ ಸಲಹೆಗಳು",
        privacy_policy: "ಖಾಸಗಿತನದ ನೀತಿ",
        "How to Identify Leaf Spot Disease": "ಎಲೆ ಚುಕ್ಕೆ ರೋಗವನ್ನು ಪತ್ತೆಹಚ್ಚುವುದು ಹೇಗೆ",
        "Disease Guide": "ರೋಗ ಮಾರ್ಗದರ್ಶಿ",
        "5 min read": "5 ನಿಮಿಷದ ಓದು",
        "Best Fertilizers for Arecanut": "ಅಡಿಕೆಗೆ ಅತ್ಯುತ್ತಮ ರಸಗೊಬ್ಬರಗಳು",
        "Nutrients": "ಪೋಷಕಾಂಶಗಳು",
        "3 min read": "3 ನಿಮಿಷದ ಓದು",
        "Irrigation Techniques for Better Yield": "ಉತ್ತಮ ಇಳುವರಿಗಾಗಿ ನೀರಾವರಿ ತಂತ್ರಗಳು",
        "Water Management": "ನೀರಿನ ನಿರ್ವಹಣೆ",
        "4 min read": "4 ನಿಮಿಷದ ಓದು",
        "Seasonal Care for Arecanut Palms": "ಅಡಿಕೆ ಮರಗಳಿಗೆ ಕಾಲೋಚಿತ ಆರೈಕೆ",
        "Maintenance": "ನಿರ್ವಹಣೆ",
        "6 min read": "6 ನಿಮಿಷದ ಓದು"
    }
};

// Fallback to English for unsupported languages
const getTransl = (lang, key) => {
    const dict = translations[lang] || translations['en'];
    return dict[key] || translations['en'][key] || key;
};

export const LanguageContext = createContext();

export const useLanguage = () => useContext(LanguageContext);

export const LanguageProvider = ({ children }) => {
    const [language, setLanguage] = useState('en');
    const [isLoaded, setIsLoaded] = useState(false);

    useEffect(() => {
        const loadLang = async () => {
            try {
                const saved = await SecureStore.getItemAsync('app_language');
                if (saved) setLanguage(saved);
            } catch (error) { }
            finally { setIsLoaded(true); }
        };
        loadLang();
    }, []);

    const changeLanguage = async (val) => {
        setLanguage(val);
        await SecureStore.setItemAsync('app_language', val);
    };

    const t = (key) => getTransl(language, key);

    if (!isLoaded) return null;

    return (
        <LanguageContext.Provider value={{ language, changeLanguage, t }}>
            {children}
        </LanguageContext.Provider>
    );
};
